# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180527_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('pc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product_category')),
            ],
        ),
    ]
