# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products')),
                ('u_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserProfile')),
            ],
        ),
    ]
