# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_selected_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected_products',
            name='p_pk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='selected_products',
            name='u_pk',
            field=models.IntegerField(),
        ),
    ]
