# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180716_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='selected_productss',
        ),
    ]
