# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_selected_productss'),
    ]

    operations = [
        migrations.CreateModel(
            name='selection',
            fields=[
             #   ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cat', models.IntegerField()),
                ('product_cat', models.IntegerField()),
                ('product_pk', models.IntegerField()),
            ],
        ),
    ]
